# Generated by Django 2.2.6 on 2020-02-02 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_positionpaper_graded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=64)),
                ('room_number', models.IntegerField()),
                ('number_of_seats', models.IntegerField(default=20)),
            ],
            options={
                'db_table': 'room',
                'ordering': ['building_name', 'room_number'],
                'unique_together': {('building_name', 'room_number')},
            },
        ),
        migrations.AddField(
            model_name='delegate',
            name='seat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='paper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PositionPaper'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='rubric',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Rubric'),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_10_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_10_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_1_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_1_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_2_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_2_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_3_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_3_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_4_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_4_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_5_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_5_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_6_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_6_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_7_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_7_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_8_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_8_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_9_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='chair_9_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='committeefeedback',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='countrypreference',
            name='country',
            field=models.ForeignKey(limit_choices_to={'special': False}, on_delete=django.db.models.deletion.CASCADE, to='core.Country'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='published_summary',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='summary',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='positionpaper',
            name='file',
            field=models.FileField(null=True, upload_to='position_papers/'),
        ),
        migrations.AlterField(
            model_name='positionpaper',
            name='graded_file',
            field=models.FileField(blank=True, null=True, upload_to='graded_papers/'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='country_preferences',
            field=models.ManyToManyField(blank=True, through='core.CountryPreference', to='core.Country'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='num_chinese_speaking_delegates',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='grade_category_1',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='grade_category_2',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='grade_category_3',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='grade_category_4',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='grade_category_5',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='grade_t2_category_1',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='grade_t2_category_2',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='grade_t2_category_3',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='grade_t2_category_4',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='grade_t2_category_5',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='topic_one',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='topic_two',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='school',
            name='primary_gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other'), (4, 'Unspecified')], default=4),
        ),
        migrations.AlterField(
            model_name='school',
            name='primary_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Faculty'), (1, 'Student')], default=2),
        ),
        migrations.AlterField(
            model_name='school',
            name='program_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Club'), (2, 'Class')], default=1),
        ),
        migrations.AlterField(
            model_name='school',
            name='secondary_gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other'), (4, 'Unspecified')], default=4),
        ),
        migrations.AlterField(
            model_name='school',
            name='secondary_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Faculty'), (1, 'Student')], default=2),
        ),
        migrations.AlterField(
            model_name='secretariatmember',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='delegate',
            unique_together={('seat',)},
        ),
        migrations.CreateModel(
            name='RoomComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50000)),
                ('rating', models.IntegerField()),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Room')),
            ],
            options={
                'db_table': 'room_comment',
            },
        ),
        migrations.AddField(
            model_name='committee',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Room'),
        ),
    ]
